# Generated by Django 3.2.15 on 2022-09-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='directions',
            field=models.CharField(blank=True, max_length=228, null=True),
        ),
    ]
